#!/usr/bin/env python # 

class Profiler:
    
    def __init__(self, assetList):
        from yahooquery import Ticker
        self.assetList = assetList
        ticker = Ticker(assetList)
        sectors = {}
